Update README.md
melexis/mlx90632-example pull request #5
Opened 2019-05-02 14:36 UTC by Geromino

need Resistor on pin PB9 ------> I2C1_SDA internal not enough Resistor

2019-05-02 14:38 UTC, Geromino commented
how add electric scheme

2019-05-02 14:39 UTC, Letme commented
We do not need electric scheme. Just write next to the readme the remark and everyone will know what to do. Otherwise you can produce a image of scheme and add it into a folder (images?).

2019-05-02 14:42 UTC, Letme requested changes

2019-05-02 14:42 UTC, Letme commented on README.md
> +| --------------- |:----------------------:|
the `:` here are not needed and should be removed

2019-05-02 14:42 UTC, Letme commented on README.md
> +| MLX90632        |stm32f4discovery        |
add space before STM32F4 as well as separate words so it end up: `| STM32F4 Discovery`

2019-05-02 14:42 UTC, Letme commented on README.md
> +| pin 1: SDA      | p2:  pin 20: PB9      |
Add a remark about additional external resistor needed here.

2019-05-10 05:40 UTC, Letme commented
Thanks for the contribution.

2019-05-10 05:40 UTC, merged